#!/bin/sh

iname="`realpath $1`"
bname="`basename ${iname%.*}`"
mkdir -p "$bname"
cd "$bname"

cat <<EOT >/tmp/webfont-fontforge-script.pe
Open(\$1)
Generate(\$2 + ".ttf")
Generate(\$2 + ".svg")
Generate(\$2 + ".otf")
EOT

fontforge -script /tmp/webfont-fontforge-script.pe "$iname" "$bname"
sfnt2woff "$bname.otf"
ttf2eot "$bname.ttf" > "$bname.eot"

cat <<EOT >"font.css"
@font-face {
  font-family: '$bname';
  src: url('$bname.eot'); /* IE9 Compat Modes */
  src: url('$bname.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('$bname.woff') format('woff'), /* Modern Browsers */
       url('$bname.ttf')  format('truetype'), /* Safari, Android, iOS */
       url('$bname.svg#45023b575ced965d68f9dc847b2a634a') format('svg'); /* Legacy iOS */

  font-style:   normal;
  font-weight:  400;
}
EOT

cat <<EOT >"preview.html"
<!DOCTYPE html>

<head>
  <title>test</title>
  <link rel="stylesheet" type="text/css" href="font.css">
  <style type="text/css">
    body{ font-family: '$bname' }
  </style>
</head>

<body>
  <h1>$bname</h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ullamcorper justo sem. Fusce ac sem est. Aenean dignissim feugiat auctor. Vestibulum in ante sem. Ut sit amet erat arcu, eget fringilla odio. Aenean a nibh est. Cras metus urna, vulputate non feugiat vel, condimentum sit amet purus.
  </p>

  <p>
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec dictum egestas lorem. Vestibulum tempus, ante a adipiscing tempus, eros lectus mollis tellus, id viverra arcu purus vitae sapien. Suspendisse sed quam leo. Suspendisse volutpat nunc sit amet nulla venenatis ultrices. Quisque bibendum, purus pulvinar lacinia euismod, dolor tortor cursus enim, tempus porttitor magna neque in nibh. Quisque vel turpis sit amet mi semper venenatis in et arcu. Mauris mattis hendrerit turpis, tristique bibendum felis dictum et. Mauris elit turpis, suscipit eget sollicitudin id, congue sed erat. Mauris fringilla semper magna eget vulputate. Fusce ut ligula a velit ultricies condimentum at hendrerit lectus.
  </p>

  <p>
    Aliquam eget est vitae dolor consectetur condimentum. Nam at sem sapien. Donec non diam velit. Nullam felis arcu, congue sit amet vulputate ut, sagittis et tortor. Nam vulputate sodales leo non ullamcorper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tristique ante quis risus dapibus et dictum neque semper. Quisque luctus tristique odio at rutrum. Sed pretium, massa eget accumsan mollis, elit elit consequat quam, ut vulputate magna dui nec metus. Donec pharetra dictum libero eu convallis. In et molestie purus. Suspendisse rutrum fringilla magna, vulputate lobortis elit rutrum vitae. Ut pharetra dui ut mi fringilla accumsan. Nulla facilisi.
  </p>

</body>
</html>
EOT

cd ..

